"""Metadata for pathlib_gui. Generated by metametameta — do not edit by hand."""

__all__ = [
    "__credits__",
    "__description__",
    "__keywords__",
    "__license__",
    "__readme__",
    "__requires_python__",
    "__status__",
    "__title__",
    "__version__",
]

__title__ = "pathlib_gui"
__version__ = "0.1.0"
__description__ = "Tkinter gui for all the filesystem related things in the python standard library"
__readme__ = "README.md"
__credits__ = [{"name": "Matthew Martin", "email": "matthewdeanmartin@gmail.com"}]
__keywords__ = ["pathlib_gui"]
__license__ = "MIT"
__requires_python__ = ">=3.9"
__status__ = "3 - Alpha"
